---
# See https://quarkus.io/guides/deploying-to-kubernetes#using-existing-resources
# Add permissions for managing secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configreconciler-cluster-role-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configreconciler-cluster-role-binding-secrets
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: configreconciler-cluster-role-secrets
subjects:
  - kind: ServiceAccount
    name: extdb-quarkus-operator-operator
